{% set name = "jaraco.collections" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56304fd4bd4eb8d585ce0cace0ac80418791b140851e374812541b0aa27c91d0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=56
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >=3.7
    - jaraco.text
    - jaraco.classes

test:
  imports:
    - jaraco.collections

about:
  home: https://github.com/jaraco/jaraco.collections
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Models and classes to supplement the stdlib 'collections' module.
  doc_url: https://jaracocollections.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.collections

extra:
  recipe-maintainers:
    - carlodri
