{% set name = "jaraco.collections" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaraco_collections-{{ version }}.tar.gz
  sha256: 0e4829409d39ad18a40aa6754fee2767f4d9730c4ba66dc9df89f1d2756994c2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=56
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >=3.7
    - jaraco.text
    - jaraco.classes

test:
  imports:
    - jaraco.collections

about:
  home: https://github.com/jaraco/jaraco.collections
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Models and classes to supplement the stdlib 'collections' module.
  doc_url: https://jaracocollections.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.collections

extra:
  recipe-maintainers:
    - carlodri
