{% set name = "jaraco.collections" %}
{% set version = "5.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaraco_collections-{{ version }}.tar.gz
  sha256: dab81970bad6f0ab53b20745f1b01da37926e4c0fcd425046aa45e0d8efa18ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=56
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >={{ python_min }}
    - jaraco.text
    - jaraco.classes

test:
  requires:
    - python {{ python_min }}
  imports:
    - jaraco.collections

about:
  home: https://github.com/jaraco/jaraco.collections
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Models and classes to supplement the stdlib 'collections' module.
  doc_url: https://jaracocollections.readthedocs.io/
  dev_url: https://github.com/jaraco/jaraco.collections

extra:
  recipe-maintainers:
    - carlodri
